<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\BooksController::index'], [], [['text', '/']], [], []],
    'import-books' => [[], ['_controller' => 'App\\Controller\\BooksController::importBooks'], [], [['text', '/import-books']], [], []],
    'find-by-isbn' => [['isbn'], ['_controller' => 'App\\Controller\\BooksController::findByIsbn'], [], [['variable', '/', '[^/]++', 'isbn', true], ['text', '/isbn']], [], []],
    'find-all-by-category' => [['category'], ['_controller' => 'App\\Controller\\BooksController::findAllByCategory'], [], [['variable', '/', '[^/]++', 'category', true], ['text', '/category']], [], []],
    'find-published-before-date' => [['date'], ['_controller' => 'App\\Controller\\BooksController::findAByPublishedBeforeDate'], [], [['variable', '/', '[^/]++', 'date', true], ['text', '/published-before']], [], []],
    'find-all-books' => [[], ['_controller' => 'App\\Controller\\BooksController::findAll'], [], [['text', '/find-all-books']], [], []],
    'create-new-book' => [[], ['_controller' => 'App\\Controller\\BooksController::createNewBook'], [], [['text', '/create-new-book']], [], []],
    'delete-book' => [['id'], ['_controller' => 'App\\Controller\\BooksController::deleteBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
